### ISSUE TITLE
related: bsdiff port for esp32

### ISSUE THREAD

**Issue by greenaddress** [ESP32-Musings/esp32_compressed_delta_ota_update#3]
Hi,

I was looking at this project to add support for OTA firmware delta compressed support to one project I'm working on and I really liked the work you have put here and started playing with the code.

Ultimately we decided to switch to a slightly modified version of bsdiff/bspatch because the esp32 has already tinfl_decompress available (in the ROM!) and so DEFLATE can be used and using that with bsdiff was simpler than with detools. Nothing wrong with heatshrink but we already used tinfl_decompress for normal full otas so we figured reuse was a good way vs heatshrink to reduce  [slightly] firmware size (at the partition level at least).

If people are interested the port of bsdiff is available at https://github.com/Blockstream/esp32_bsdiff

Feel free to close if you consider this spamming :-)

**Comment by laukik-hase** [comment]
Hello, @greenaddress!

Thank you for the link. Glad the project helped you!
I will close this issue but will add your project's link (great work!) to the README of this project for future reference.
